var _ = require("lodash");

var opAlternates = {
  eq: "=",
  lt: "<",
  gt: ">",
  or: "||",
  and: "&&",
  xor: "^^",
  not: "!"
};

var reservedWords = [
  "and",
  "or",
  "not",
  "eq",
  "lt",
  "gt",
  "if",
  "elseif",
  "else",
  "for",
  "switch",
  "repeat",
  "while",
  "end",
  "function",
  "until",
  "in",
  "to",
  "downto",
  "default",
  "case",
  "return",
  "break",
  "breakif",
  "continueif",
  "continue"
];

var standardTypes = [
  "assoc",
  "boolean",
  "bytes",
  "cachetree",
  "capiconnect",
  "capierr",
  "capilog",
  "capilogin",
  "dapinode",
  "dapisession",
  "dapistream",
  "dapiversion",
  "date",
  "dialog",
  "domattr",
  "domcdatasection",
  "domcharacterdata",
  "domcomment",
  "domdocument",
  "domdocumentfragment",
  "domdocumenttype",
  "domelement",
  "domentity",
  "domentityreference",
  "domimplementation",
  "domnamednodemap",
  "domnode",
  "domnodelist",
  "domnotation",
  "domparser",
  "domprocessinginstruction",
  "domtext",
  "dynamic",
  "error",
  "file",
  "filecopy",
  "fileprefs",
  "frame",
  "guid",
  "integer",
  "javaobject",
  "list",
  "long",
  "mailmessage",
  "object",
  "objref",
  "patchange",
  "patfind",
  "pattern",
  "real",
  "recarray",
  "record",
  "regex",
  "saxparser",
  "script",
  "socket",
  "string",
  "uapisession",
  "uapiuser",
  "ulong",
  "wapimap",
  "wapimaptask",
  "wapisession",
  "wapisubwork",
  "wapiwork",
  "xslprocessor"
];

var declarations = [
  "IsNotSet",
  "IsSet",
  "Point",
  "PointH",
  "PointV",
  "BooleanType",
  "BytesType",
  "DateType",
  "DynamicType",
  "ErrorType",
  "ExternType",
  "IntegerType",
  "ListType",
  "ObjectType",
  "ObjRefType",
  "PointType",
  "RealType",
  "ScriptType",
  "StringType",
  "Undefined",
  "UndefinedType",
  "VoidType",
  "DatatypeName",
  "Echo",
  "EchoDebug",
  "EchoError",
  "EchoInfo",
  "EchoStamp",
  "EchoWarn",
  "GetFeatures",
  "IsDefined",
  "IsError",
  "IsFeature",
  "IsInvokable",
  "IsNotError",
  "IsNotSet",
  "IsObject",
  "IsSet",
  "IsUndefined",
  "Length",
  "NParameters",
  "Parameters",
  "Point",
  "PointH",
  "PointV",
  "Type"
];

module.exports = {
  builtin_types: standardTypes,
  reserved_words: reservedWords,
  op_alternates: opAlternates,
  declarations: _.map(declarations, function(v) {
    return { value: v };
  })
};
