var _ = require("lodash");

var opAlternates = {
  eq: "=",
  lt: "<",
  gt: ">",
  or: "||",
  and: "&&",
  xor: "^^",
  not: "!"
};

var reservedWords = [
  "and",
  "or",
  "not",
  "eq",
  "lt",
  "gt",
  "if",
  "elseif",
  "else",
  "for",
  "switch",
  "repeat",
  "while",
  "end",
  "function",
  "until",
  "in",
  "to",
  "downto",
  "default",
  "case",
  "return",
  "break",
  "breakif",
  "continueif",
  "continue",
  "goto"
];

var standardTypes = [
  "Assoc",
  "Boolean",
  "Builder",
  "Bytes",
  "CAPI",
  "CAPICONNECT",
  "CAPIERR",
  "CAPILOG",
  "CAPILOGIN",
  "CacheTree",
  "Compiler",
  "Core",
  "DAPI",
  "DAPINODE",
  "DAPISESSION",
  "DAPISTREAM",
  "DAPIVERSION",
  "DOMAttr",
  "DOMCDATASection",
  "DOMCharacterData",
  "DOMComment",
  "DOMDocument",
  "DOMDocumentFragment",
  "DOMDocumentType",
  "DOMElement",
  "DOMEntity",
  "DOMEntityReference",
  "DOMImplementation",
  "DOMNamedNodeMap",
  "DOMNode",
  "DOMNodeList",
  "DOMNotation",
  "DOMParser",
  "DOMProcessingInstruction",
  "DOMText",
  "Date",
  "Dynamic",
  "Env",
  "Error",
  "File",
  "FileCopy",
  "Fileprefs",
  "Frame",
  "Global",
  "Integer",
  "JavaObject",
  "Language",
  "License",
  "List",
  "Logging",
  "Long",
  "MailMessage",
  "Math",
  "Memcached",
  "NotSet",
  "OTDS",
  "ObjRef",
  "Object",
  "POP3Session",
  "PatChange",
  "PatFind",
  "Pattern",
  "Point",
  "Real",
  "RecArray",
  "Record",
  "Regex",
  "RestClient",
  "SAXParser",
  "SMTPSession",
  "SSLOptions",
  "Script",
  "Security",
  "Set",
  "Socket",
  "sql",
  "SqlConnection",
  "SqlCursor",
  "Str",
  "String",
  "System",
  "UAPI",
  "UAPISESSION",
  "UAPIUSER",
  "Void",
  "WAPI",
  "WAPIMAP",
  "WAPIMAPTASK",
  "WAPISESSION",
  "WAPISUBWORK",
  "WAPIWORK",
  "Web",
  "XSLProcessor",
  "Zip"
];

var declarations = [
  "IsNotSet",
  "IsSet",
  "Point",
  "PointH",
  "PointV",
  "BooleanType",
  "BytesType",
  "DateType",
  "DynamicType",
  "ErrorType",
  "ExternType",
  "IntegerType",
  "ListType",
  "ObjectType",
  "ObjRefType",
  "PointType",
  "RealType",
  "ScriptType",
  "StringType",
  "Undefined",
  "UndefinedType",
  "VoidType",
  "DatatypeName",
  "Echo",
  "EchoDebug",
  "EchoError",
  "EchoInfo",
  "EchoStamp",
  "EchoWarn",
  "GetFeatures",
  "IsDefined",
  "IsError",
  "IsFeature",
  "IsInvokable",
  "IsNotError",
  "IsNotSet",
  "IsObject",
  "IsSet",
  "IsUndefined",
  "Length",
  "NParameters",
  "Parameters",
  "Point",
  "PointH",
  "PointV",
  "Type"
];

module.exports = {
  builtin_types: _.map(standardTypes, function(v) {
    return v.toLowerCase();
  }),
  reserved_words: reservedWords,
  op_alternates: opAlternates,
  declarations: _.map(declarations, function(v) {
    return { value: v };
  })
};
